package com.mikeyphw.xdm.android

import com.mikeyphw.xdm.android.browserextension.BrowserExtensionSourceContract

fun XdmThemeMode.toBrowserExtensionThemeMode(): BrowserExtensionSourceContract.ThemeMode = when (this) {
    XdmThemeMode.Dark -> BrowserExtensionSourceContract.ThemeMode.Dark
    XdmThemeMode.Amoled -> BrowserExtensionSourceContract.ThemeMode.Amoled
}

data class BrowserExtensionExportPreferences(
    val exportTreeUri: String = "",
    val defaultTarget: BrowserExtensionSourceContract.Target = BrowserExtensionSourceContract.Target.Xdm,
    val requestedTheme: BrowserExtensionSourceContract.ThemeSelection = BrowserExtensionSourceContract.ThemeSelection.FollowApp,
    val lastExportTheme: BrowserExtensionSourceContract.ThemeMode? = null,
    val lastExportAppVersion: String = "",
    val lastExportExtensionVersion: String = "",
    val lastExportSha256: String = "",
    val lastExportEpochMs: Long = 0L,
    val lastExportFileName: String = "",
    val lastExportByteCount: Long = 0L,
    val lastExportDocumentUri: String = "",
    val lastExportTarget: BrowserExtensionSourceContract.Target? = null,
    val lastExportApplicationId: String = "",
    val lastExportScheme: String = "",
    val lastExportContractVersion: Int = 0,
) {
    fun resolvedTheme(appTheme: XdmThemeMode): BrowserExtensionSourceContract.ThemeMode =
        requestedTheme.resolve(appTheme.toBrowserExtensionThemeMode())

    fun isThemeStale(appTheme: XdmThemeMode): Boolean =
        lastExportFileName.isNotBlank() && lastExportTheme != resolvedTheme(appTheme)

    fun staleReasons(
        appTheme: XdmThemeMode,
        appVersion: String,
        applicationId: String,
        scheme: String,
    ): List<String> = buildList {
        if (lastExportFileName.isBlank()) return@buildList
        if (lastExportTheme != resolvedTheme(appTheme)) add("Generated theme no longer matches the selected app theme.")
        if (lastExportTarget != defaultTarget) add("Default launch target changed after the last export.")
        if (lastExportExtensionVersion != BrowserExtensionSourceContract.DevelopmentVersion) add("Extension source version changed after the last export.")
        if (lastExportContractVersion != BrowserExtensionSourceContract.ContractVersion) add("Extension and app contract versions differ.")
        if (lastExportApplicationId != applicationId || lastExportScheme != scheme) add("The exported XPI targets another XDM app variant.")
        if (lastExportAppVersion != appVersion) add("The XPI was generated by XDM $lastExportAppVersion instead of $appVersion.")
    }

    fun isCurrent(appTheme: XdmThemeMode, appVersion: String, applicationId: String, scheme: String): Boolean =
        lastExportFileName.isNotBlank() && staleReasons(appTheme, appVersion, applicationId, scheme).isEmpty()
}

enum class BrowserExtensionExportPhase {
    Idle,
    Exporting,
    Succeeded,
    Failed,
}

data class BrowserExtensionRuntimeStatus(
    val phase: BrowserExtensionExportPhase = BrowserExtensionExportPhase.Idle,
    val message: String = "Choose an export folder to generate the Firefox XPI.",
    val exportedUri: String = "",
)
