using XDM.Core.Downloads;

namespace XDM.Core.Persistence;

public sealed record PersistedDownload(
    string Id,
    Uri Source,
    string DestinationPath,
    long DownloadedBytes,
    long? TotalBytes,
    DownloadState State,
    DateTimeOffset UpdatedAt,
    string? ErrorMessage = null,
    string QueueId = "default",
    string? CategoryId = null,
    int QueueOrder = 0,
    string? EntityTag = null,
    DateTimeOffset? LastModified = null,
    int ConnectionCount = 4,
    string Method = "GET",
    DownloadPriority Priority = DownloadPriority.Normal,
    Uri? SourcePage = null,
    string? ExpectedChecksumAlgorithm = null,
    string? ExpectedChecksum = null,
    string? ActualChecksum = null,
    DateTimeOffset? LastVerifiedAt = null,
    DownloadIntegrityStatus IntegrityStatus = DownloadIntegrityStatus.Unknown,
    bool RecoveryRequired = false,
    string? RecoveryMessage = null,
    IReadOnlyList<Uri>? Mirrors = null,
    DownloadBackendPreference BackendPreference = DownloadBackendPreference.Automatic,
    DownloadBackendKind Backend = DownloadBackendKind.Native,
    string? BackendTaskId = null,
    string? BackendDecisionReason = null,
    bool AllowBackendFallback = true);
