package com.mikeyphw.xdm.android.media

import com.mikeyphw.xdm.android.model.MediaCaptureRecord
import com.mikeyphw.xdm.android.model.MediaResolutionStatus
import com.mikeyphw.xdm.android.model.MediaSourceKind
import com.mikeyphw.xdm.android.model.MediaVariant
import com.mikeyphw.xdm.android.model.MediaVariantKind
import java.net.URI
import java.net.URLDecoder
import java.net.URLEncoder
import java.nio.charset.StandardCharsets
import java.util.Locale

enum class MediaResolverStage(val label: String) {
    Source("Source"),
    Probe("Probe"),
    Streams("Streams"),
    Selection("Selection"),
    Review("Review"),
    Ready("Ready"),
    Protected("Protected"),
    Failed("Failed"),
}

data class MediaResolverFormatRow(
    val variantId: String,
    val title: String,
    val detail: String,
    val resolutionLabel: String?,
    val codecLabel: String?,
    val containerLabel: String?,
    val bitrateLabel: String?,
    val estimatedSizeBytes: Long?,
    val estimatedSizeLabel: String?,
    val hdr: Boolean,
    val selected: Boolean,
    val recommendations: List<String>,
)

data class MediaResolverTrackRow(
    val variantId: String,
    val title: String,
    val detail: String,
    val languageLabel: String,
    val selected: Boolean,
    val autoGenerated: Boolean = false,
    val forced: Boolean = false,
)

data class MediaResolverProbeDashboard(
    val extractorLabel: String,
    val statusLabel: String,
    val formatCount: Int,
    val authenticationLabel: String,
    val warnings: List<String>,
    val probeTargetLabel: String,
)

data class MediaResolverSessionDashboard(
    val referrerHost: String?,
    val cookiesAvailable: Boolean,
    val authorizationAvailable: Boolean,
    val customHeaderCount: Int,
    val userAgentAvailable: Boolean,
    val redactedSummary: String,
)

data class MediaResolverHistoryRow(
    val captureId: String,
    val title: String,
    val sourceHost: String,
    val kindLabel: String,
    val selectionSummary: String,
    val statusLabel: String,
    val updatedAtEpochMs: Long,
)

data class MediaResolverWorkspace(
    val captureId: String,
    val stage: MediaResolverStage,
    val stageSequence: List<MediaResolverStage>,
    val sourceLabel: String,
    val summary: String,
    val formats: List<MediaResolverFormatRow>,
    val audioTracks: List<MediaResolverTrackRow>,
    val subtitleTracks: List<MediaResolverTrackRow>,
    val selectedSummary: String,
    val readyToQueue: Boolean,
    val probe: MediaResolverProbeDashboard,
    val session: MediaResolverSessionDashboard,
    val protectedDiagnostic: ProtectedMediaDiagnostic,
    val comparisonNotes: List<String>,
)

object MediaTrackSelectionCodec {
    private const val Separator = "|"

    fun encode(selection: MediaTrackSelection): String = listOf(
        selection.videoVariantId,
        selection.audioVariantId,
        selection.subtitleVariantId,
    ).joinToString(Separator) { value -> URLEncoder.encode(value.orEmpty(), StandardCharsets.UTF_8.name()) }

    fun decode(encoded: String): MediaTrackSelection? {
        val parts = encoded.split(Separator)
        if (parts.size != 3) return null
        fun part(index: Int): String? = URLDecoder.decode(parts[index], StandardCharsets.UTF_8.name()).takeIf { it.isNotBlank() }
        return MediaTrackSelection(part(0), part(1), part(2))
    }
}

class MediaResolverWorkspacePlanner(
    private val downloadPlanner: MediaDownloadPlanner = MediaDownloadPlanner(),
) {
    fun workspace(
        capture: MediaCaptureRecord,
        variants: List<MediaVariant>,
        selection: MediaTrackSelection = MediaTrackSelection(videoVariantId = capture.selectedVariantId),
        sessionHeaders: List<MediaSessionHeader> = MediaDownloadPlanner.defaultSessionHeaders(capture),
    ): MediaResolverWorkspace {
        val plan = downloadPlanner.plan(capture, variants, selection = selection, sessionHeaders = sessionHeaders)
        val normalized = plan.trackSelection
        val videoVariants = variants.filter { it.kind == MediaVariantKind.Video || it.kind == MediaVariantKind.Primary }
            .sortedWith(compareByDescending<MediaVariant> { it.height ?: 0 }.thenByDescending { it.bitrateBitsPerSecond ?: 0L })
        val audioVariants = variants.filter { it.kind == MediaVariantKind.Audio }
            .sortedWith(compareBy<MediaVariant> { it.language.orEmpty() }.thenByDescending { it.bitrateBitsPerSecond ?: 0L })
        val subtitleVariants = variants.filter { it.kind == MediaVariantKind.Subtitle }
            .sortedWith(compareBy<MediaVariant> { it.language.orEmpty() }.thenBy { it.position })
        val selectedVideo = videoVariants.firstOrNull { it.id == normalized.videoVariantId }
        val selectedAudio = audioVariants.firstOrNull { it.id == normalized.audioVariantId }
        val selectedSubtitle = subtitleVariants.firstOrNull { it.id == normalized.subtitleVariantId }
        val ready = plan.canQueueDirectly && when {
            capture.kind == MediaSourceKind.HlsPlaylist || capture.kind == MediaSourceKind.DashManifest -> videoVariants.isNotEmpty() || variants.isNotEmpty()
            capture.pageUrl != null && capture.kind == MediaSourceKind.Unknown -> capture.resolutionStatus == MediaResolutionStatus.Resolved
            else -> true
        }
        val stage = stageFor(capture, variants, selection, plan, ready)
        val formatRows = videoVariants.map { variant ->
            formatRow(
                variant = variant,
                durationMs = capture.durationMs,
                selected = variant.id == normalized.videoVariantId,
                bestHeight = videoVariants.maxOfOrNull { it.height ?: 0 } ?: 0,
                smallestEstimate = videoVariants.mapNotNull { estimateSize(it, capture.durationMs) }.minOrNull(),
            )
        }
        val audioRows = audioVariants.map { trackRow(it, it.id == normalized.audioVariantId) }
        val subtitleRows = subtitleVariants.map { trackRow(it, it.id == normalized.subtitleVariantId) }
        val session = sessionDashboard(plan.sessionHandoff)
        val probeWarnings = buildList {
            if (capture.resolutionStatus == MediaResolutionStatus.RequiresRefresh) add("Manifest metadata has expired and should be refreshed before queueing.")
            if (capture.resolutionStatus == MediaResolutionStatus.Failed) add("The previous resolver attempt failed. Review diagnostics before retrying.")
            if (capture.isPlaylist && variants.isEmpty()) add("Adaptive media has no resolved streams yet.")
            if (capture.pageUrl != null && variants.isEmpty()) add("Page sources need a yt-dlp metadata probe before format selection.")
            if (plan.protectedDiagnostic.protected) add("Protected media remains diagnostic-only; XDM does not bypass DRM.")
        }
        val extractor = when {
            capture.pageUrl != null -> "Page extractor"
            capture.kind == MediaSourceKind.HlsPlaylist -> "HLS manifest"
            capture.kind == MediaSourceKind.DashManifest -> "DASH manifest"
            else -> capture.kind.name.replace(Regex("([a-z])([A-Z])"), "$1 $2")
        }
        val comparisonNotes = comparisonNotes(formatRows)
        return MediaResolverWorkspace(
            captureId = capture.id,
            stage = stage,
            stageSequence = listOf(MediaResolverStage.Source, MediaResolverStage.Probe, MediaResolverStage.Streams, MediaResolverStage.Selection, MediaResolverStage.Review, MediaResolverStage.Ready),
            sourceLabel = hostOf(capture.pageUrl ?: capture.sourceUrl),
            summary = listOfNotNull(
                capture.title.ifBlank { capture.fileName },
                capture.durationMs?.let(::durationLabel),
                variants.size.takeIf { it > 0 }?.let { "$it streams" },
                selectedVideo?.qualityLabel,
            ).joinToString(" • "),
            formats = formatRows,
            audioTracks = audioRows,
            subtitleTracks = subtitleRows,
            selectedSummary = selectedSummary(selectedVideo, selectedAudio, selectedSubtitle),
            readyToQueue = ready,
            probe = MediaResolverProbeDashboard(
                extractorLabel = extractor,
                statusLabel = when {
                    plan.protectedDiagnostic.protected -> "Protected"
                    capture.resolutionStatus == MediaResolutionStatus.Failed -> "Failed"
                    capture.resolutionStatus == MediaResolutionStatus.RequiresRefresh -> "Refresh required"
                    variants.isNotEmpty() || !capture.isPlaylist -> "Ready"
                    else -> "Probe required"
                },
                formatCount = variants.size.coerceAtLeast(capture.variantCount),
                authenticationLabel = when {
                    session.cookiesAvailable || session.authorizationAvailable -> "Session available (redacted)"
                    session.referrerHost != null -> "Referrer context available"
                    else -> "No authentication context"
                },
                warnings = probeWarnings,
                probeTargetLabel = if (capture.pageUrl != null) "External page" else "Direct media source",
            ),
            session = session,
            protectedDiagnostic = plan.protectedDiagnostic,
            comparisonNotes = comparisonNotes,
        )
    }

    fun history(
        captures: List<MediaCaptureRecord>,
        variants: List<MediaVariant>,
        selections: Map<String, MediaTrackSelection> = emptyMap(),
        limit: Int = 8,
    ): List<MediaResolverHistoryRow> = captures
        .sortedByDescending { it.updatedAtEpochMs }
        .take(limit.coerceAtLeast(0))
        .map { capture ->
            val captureVariants = variants.filter { it.captureId == capture.id }
            val selection = selections[capture.id] ?: MediaTrackSelection(videoVariantId = capture.selectedVariantId)
            val plan = downloadPlanner.plan(capture, captureVariants, selection = selection)
            MediaResolverHistoryRow(
                captureId = capture.id,
                title = capture.title.ifBlank { capture.fileName },
                sourceHost = hostOf(capture.pageUrl ?: capture.sourceUrl),
                kindLabel = capture.kind.name.replace(Regex("([a-z])([A-Z])"), "$1 $2"),
                selectionSummary = selectionSummary(captureVariants, plan.trackSelection),
                statusLabel = when {
                    plan.protectedDiagnostic.protected -> "Protected"
                    capture.downloadId != null -> "Queued"
                    capture.resolutionStatus == MediaResolutionStatus.Resolved -> "Resolved"
                    capture.resolutionStatus == MediaResolutionStatus.RequiresRefresh -> "Refresh required"
                    capture.resolutionStatus == MediaResolutionStatus.Failed -> "Failed"
                    else -> "Waiting for probe"
                },
                updatedAtEpochMs = capture.updatedAtEpochMs,
            )
        }

    private fun stageFor(
        capture: MediaCaptureRecord,
        variants: List<MediaVariant>,
        selection: MediaTrackSelection,
        plan: MediaDownloadPlan,
        ready: Boolean,
    ): MediaResolverStage = when {
        plan.protectedDiagnostic.protected -> MediaResolverStage.Protected
        capture.resolutionStatus == MediaResolutionStatus.Failed -> MediaResolverStage.Failed
        capture.resolutionStatus == MediaResolutionStatus.RequiresRefresh -> MediaResolverStage.Probe
        capture.isPlaylist && variants.isEmpty() -> MediaResolverStage.Probe
        variants.isEmpty() -> if (ready) MediaResolverStage.Review else MediaResolverStage.Probe
        selection.selectedIds().isEmpty() && variants.any { it.kind != MediaVariantKind.Thumbnail } -> MediaResolverStage.Selection
        ready -> MediaResolverStage.Ready
        else -> MediaResolverStage.Review
    }

    private fun formatRow(
        variant: MediaVariant,
        durationMs: Long?,
        selected: Boolean,
        bestHeight: Int,
        smallestEstimate: Long?,
    ): MediaResolverFormatRow {
        val estimate = estimateSize(variant, durationMs)
        val codec = variant.codecs?.takeIf { it.isNotBlank() }
        val codecLower = codec.orEmpty().lowercase(Locale.US)
        val hdr = variant.displayLabel.contains("hdr", ignoreCase = true) || codecLower.contains("hdr") || codecLower.contains("dvhe")
        val recommendations = buildList {
            if ((variant.height ?: 0) == bestHeight && bestHeight > 0) add("Best quality")
            if (codecLower.contains("avc") || codecLower.contains("h264") || variant.mimeType?.contains("mp4", ignoreCase = true) == true) add("Compatible")
            if (codecLower.contains("av01") || codecLower.contains("av1") || codecLower.contains("vp9") || codecLower.contains("hevc") || codecLower.contains("h265")) add("Efficient")
            if (estimate != null && estimate == smallestEstimate) add("Compact")
            if (hdr) add("HDR")
        }.distinct()
        val resolution = when {
            variant.width != null && variant.height != null -> "${variant.width}×${variant.height}"
            variant.height != null -> "${variant.height}p"
            else -> null
        }
        return MediaResolverFormatRow(
            variantId = variant.id,
            title = variant.qualityLabel,
            detail = listOfNotNull(resolution, codec, variant.mimeType).joinToString(" • ").ifBlank { "Video stream" },
            resolutionLabel = resolution,
            codecLabel = codec,
            containerLabel = containerLabel(variant),
            bitrateLabel = variant.bitrateBitsPerSecond?.takeIf { it > 0 }?.let(::bitrateLabel),
            estimatedSizeBytes = estimate,
            estimatedSizeLabel = estimate?.let(::sizeLabel),
            hdr = hdr,
            selected = selected,
            recommendations = recommendations,
        )
    }

    private fun trackRow(variant: MediaVariant, selected: Boolean): MediaResolverTrackRow {
        val label = variant.displayLabel.ifBlank { variant.qualityLabel }
        val lower = label.lowercase(Locale.US)
        val details = listOfNotNull(
            variant.codecs,
            variant.bitrateBitsPerSecond?.takeIf { it > 0 }?.let(::bitrateLabel),
            variant.mimeType,
        ).joinToString(" • ").ifBlank { variant.kind.name }
        return MediaResolverTrackRow(
            variantId = variant.id,
            title = label,
            detail = details,
            languageLabel = variant.language?.takeIf { it.isNotBlank() } ?: "Undetermined language",
            selected = selected,
            autoGenerated = lower.contains("auto") || lower.contains("generated"),
            forced = lower.contains("forced"),
        )
    }

    private fun sessionDashboard(handoff: MediaSessionHandoff): MediaResolverSessionDashboard {
        val authorization = handoff.headers.any { it.name.equals("Authorization", ignoreCase = true) }
        val userAgent = handoff.headers.any { it.name.equals("User-Agent", ignoreCase = true) }
        val customHeaders = handoff.headers.count {
            !it.name.equals("Cookie", ignoreCase = true) &&
                !it.name.equals("Authorization", ignoreCase = true) &&
                !it.name.equals("User-Agent", ignoreCase = true)
        }
        return MediaResolverSessionDashboard(
            referrerHost = handoff.referer?.let(::hostOf),
            cookiesAvailable = handoff.cookieHeaderAvailable,
            authorizationAvailable = authorization,
            customHeaderCount = customHeaders,
            userAgentAvailable = userAgent,
            redactedSummary = handoff.redactedSummary,
        )
    }

    private fun selectedSummary(video: MediaVariant?, audio: MediaVariant?, subtitle: MediaVariant?): String = listOfNotNull(
        video?.let { "Video ${it.qualityLabel}" },
        audio?.let { "Audio ${it.language ?: it.qualityLabel}" },
        subtitle?.let { "Subtitles ${it.language ?: it.qualityLabel}" },
    ).joinToString(" • ").ifBlank { "Automatic format selection" }

    private fun selectionSummary(variants: List<MediaVariant>, selection: MediaTrackSelection): String = selectedSummary(
        variants.firstOrNull { it.id == selection.videoVariantId },
        variants.firstOrNull { it.id == selection.audioVariantId },
        variants.firstOrNull { it.id == selection.subtitleVariantId },
    )

    private fun comparisonNotes(rows: List<MediaResolverFormatRow>): List<String> = buildList {
        rows.firstOrNull { "Best quality" in it.recommendations }?.let { add("${it.title}: highest resolved quality.") }
        rows.firstOrNull { "Compatible" in it.recommendations }?.let { add("${it.title}: broad decoder compatibility.") }
        rows.firstOrNull { "Efficient" in it.recommendations }?.let { add("${it.title}: newer codec with better compression; decoder support may vary.") }
        rows.firstOrNull { "Compact" in it.recommendations }?.let { add("${it.title}: smallest estimated transfer among resolved video formats.") }
    }.distinct().take(4)

    private fun estimateSize(variant: MediaVariant, durationMs: Long?): Long? {
        val bitrate = variant.bitrateBitsPerSecond?.takeIf { it > 0 } ?: return null
        val duration = durationMs?.takeIf { it > 0 } ?: return null
        return (bitrate.toDouble() * duration.toDouble() / 8_000.0).toLong().coerceAtLeast(0L)
    }

    private fun containerLabel(variant: MediaVariant): String? {
        val mime = variant.mimeType.orEmpty().lowercase(Locale.US)
        return when {
            "mp4" in mime -> "MP4"
            "webm" in mime -> "WebM"
            "mpegurl" in mime -> "HLS"
            "dash" in mime -> "DASH"
            else -> variant.url.substringBefore('?').substringAfterLast('.', "").takeIf { it.length in 2..5 }?.uppercase(Locale.US)
        }
    }

    private fun hostOf(url: String): String = runCatching { URI(url).host }.getOrNull()?.removePrefix("www.")?.takeIf { it.isNotBlank() } ?: "external source"

    private fun bitrateLabel(bitsPerSecond: Long): String = if (bitsPerSecond >= 1_000_000) {
        String.format(Locale.US, "%.1f Mbps", bitsPerSecond / 1_000_000.0)
    } else {
        "${bitsPerSecond / 1000} kbps"
    }

    private fun sizeLabel(bytes: Long): String {
        val gib = 1024.0 * 1024.0 * 1024.0
        val mib = 1024.0 * 1024.0
        return when {
            bytes >= gib -> String.format(Locale.US, "%.2f GB estimated", bytes / gib)
            bytes >= mib -> String.format(Locale.US, "%.1f MB estimated", bytes / mib)
            else -> "${bytes / 1024} KB estimated"
        }
    }

    private fun durationLabel(durationMs: Long): String {
        val seconds = durationMs / 1000
        val hours = seconds / 3600
        val minutes = seconds % 3600 / 60
        val remaining = seconds % 60
        return if (hours > 0) "%d:%02d:%02d".format(hours, minutes, remaining) else "%d:%02d".format(minutes, remaining)
    }
}
