"use strict";
const assert=require("assert"),fs=require("fs"),path=require("path"),vm=require("vm"),os=require("os"),childProcess=require("child_process");
const source=path.resolve(__dirname,"../src/main/extension/xdm-firefox"); const context=vm.createContext({console,URL,URLSearchParams,encodeURI,Date,setTimeout,clearTimeout,document:{baseURI:"https://page.example/watch",title:"Release"},location:{href:"https://page.example/watch"},globalThis:null}); context.globalThis=context; context.XdmExtensionConfig={contractVersion:3,xdmScheme:"xdmdownload",defaultTarget:"xdm"}; for(const file of ["detector-core.js","candidate-store.js","handoff.js"]) vm.runInContext(fs.readFileSync(path.join(source,file),"utf8"),context,{filename:file});
const core=context.XdmDetectorCoreV1,handoff=context.XdmHandoffV1; const configSource=fs.readFileSync(path.join(source,"generated-config.template.js"),"utf8"); const gradleSource=fs.readFileSync(path.resolve(__dirname,"../build.gradle.kts"),"utf8"); const prepareSource=fs.readFileSync(path.resolve(__dirname,"../tools/prepare_extension.py"),"utf8");
for(const token of ["captureKeyId","capturePublicKeySpki","captureOaepHash"]){ assert(!configSource.includes(token)); assert(!gradleSource.includes(token)); assert(!prepareSource.includes(token)); }
const temp=fs.mkdtempSync(path.join(os.tmpdir(),"xdm-v3-release-")); try { const result=childProcess.spawnSync("python3",[path.resolve(__dirname,"../tools/prepare_extension.py"),"--source",source,"--output",temp,"--channel","release","--default-target","xdm","--contract-version","3","--extension-version","1.3.0"],{encoding:"utf8"}); assert.strictEqual(result.status,0,result.stderr||result.stdout); } finally { fs.rmSync(temp,{recursive:true,force:true}); }
for(const fixture of [{url:"https://cdn.example/video",type:"media",contentType:"video/mp4"},{url:"https://cdn.example/master",type:"fetch",contentType:"application/vnd.apple.mpegurl"},{url:"https://cdn.example/manifest",type:"xmlhttprequest",contentType:"application/dash+xml"}]) assert(core.classifyResponse(fixture).accept);
assert(!core.classifyResponse({url:"https://api.example/fake.mp4",type:"fetch",contentType:"application/json"}).accept,"JSON endpoint with media-looking suffix must be rejected"); assert(!core.classifyResponse({url:"https://cdn.example/poster.mp4",type:"other",contentType:"image/jpeg"}).accept);
const capture=handoff.buildXdmCapture({url:"https://cdn.example/master.m3u8?signature=signed-a",mimeType:"application/vnd.apple.mpegurl"}); assert.match(capture,/^xdmdownload:\/\/capture\?v=3&/); assert(!/kid=|ek=|iv=|ct=/.test(capture));
const noThumbnail=new URL(handoff.buildXdmCapture({url:"https://cdn.example/video.mp4",pageUrl:"https://page.example/watch"})); assert(!noThumbnail.searchParams.has("thumbnail"),"missing thumbnail must not resolve to the page URL");
const metadataCapture=new URL(handoff.buildXdmCapture({url:"https://cdn.example/video.mp4",contentLength:734003200,durationMs:630000,thumbnailUrl:"https://cdn.example/poster.jpg"})); assert.strictEqual(metadataCapture.searchParams.get("length"),"734003200"); assert.strictEqual(metadataCapture.searchParams.get("durationMs"),"630000"); assert.strictEqual(metadataCapture.searchParams.get("thumbnail"),"https://cdn.example/poster.jpg"); console.log("browser bridge v3 release-gate tests passed");
