"use strict";
const assert=require("assert"),fs=require("fs"),vm=require("vm"),path=require("path");
const source=path.resolve(__dirname,"../src/main/extension/xdm-firefox");
const context=vm.createContext({console,URL,URLSearchParams,encodeURI,document:{baseURI:"https://page.example/watch",title:"Episode 4"},location:{href:"https://page.example/watch"},globalThis:null}); context.globalThis=context;
context.XdmExtensionConfig={contractVersion:3,xdmScheme:"xdmdownload",defaultTarget:"xdm"}; vm.runInContext(fs.readFileSync(path.join(source,"handoff.js"),"utf8"),context,{filename:"handoff.js"});
const handoff=context.XdmHandoffV1;
const capture=handoff.buildXdmCapture({url:"https://cdn.example/master.m3u8?token=abc",pageUrl:"https://page.example/watch",mimeType:"application/vnd.apple.mpegurl",stableMediaId:"browser-media-12345678",sessionRevision:9,browserHandoff:{proposedHeaders:{headers:{Referer:"https://page.example/watch",Cookie:"sid=abc"}},finalHeaders:{headers:{Authorization:"Bearer xyz","User-Agent":"IronFox"}}}});
assert.match(capture,/^xdmdownload:\/\/capture\?v=3&/); const uri=new URL(capture); assert.strictEqual(uri.searchParams.get("url"),"https://cdn.example/master.m3u8?token=abc"); assert.strictEqual(uri.searchParams.get("mime"),"application/vnd.apple.mpegurl"); assert(uri.searchParams.get("headers").includes("authorization: Bearer xyz")); assert(uri.searchParams.get("proposedHeaders").includes("cookie: sid=abc"));
const targets=handoff.buildTargets({url:"https://cdn.example/master.m3u8?token=abc"}); assert.match(targets.xdm,/^xdmdownload:\/\/add\?v=1&url=/); assert.strictEqual(handoff.buildOneDm({url:"https://cdn.example/video.mp4"}),"idmdownload:https://cdn.example/video.mp4");
console.log("direct v3 handoff tests passed");
